### ISSUE TITLE
Add baremetal node entity

### ISSUE THREAD

**Issue by chuan137** [pulumi/pulumi-openstack#121]
Hi, I think it would be nice that I can create a baremetal node entity within pulumi stack. For example, I would check the node's status, if it is already deployed as a Nova server or not.

**Comment by leezen** [comment]
From my reading of the documentation, my understanding is that you can schedule it on a specific node via `::<uuid>` when specifying the availability zone. Does this work for you?

**Comment by chuan137** [comment]
> From my reading of the documentation, my understanding is that you can schedule it on a specific node via `::<uuid>` when specifying the availability zone. Does this work for you?

yes, creating server with the node id works for me. But can I reference the baremetal node in pulumi script? The node might  already have a server or not.

**Comment by leezen** [comment]
You can retrieve the state via https://www.pulumi.com/docs/reference/pkg/openstack/compute/getinstancev2/ to see if it's already been deployed.

**Comment by chuan137** [comment]
I have not tried it out, but AFAK getInstance returns a nova server instance instead of a barmetal node
