### ISSUE TITLE
cron GHA is broken

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-openstack#211]
### What happened?

https://github.com/pulumi/pulumi-openstack/actions/runs/3880663068

### Steps to reproduce

n/a

### Expected Behavior

n/a

### Actual Behavior

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
The original issue is fixed in a PR but now getting this:

```
error: 1 error occurred:
[204](https://github.com/pulumi/pulumi-openstack/actions/runs/3889743105/jobs/6638355485#step:21:206)
      	* Error creating OpenStack server: Expected HTTP response code [201 202] when accessing [POST https://compute.uk1.cloud.ovh.net/v2.1/9d596a0506974e0f8c79673edf0bbdd3/servers], but got 409 instead
[205](https://github.com/pulumi/pulumi-openstack/actions/runs/3889743105/jobs/6638355485#step:21:207)
      {"conflictingRequest": {"code": 409, "message": "Multiple possible networks found, use a Network ID to be more specific."}}
[206](https://github.com/pulumi/pulumi-openstack/actions/runs/3889743105/jobs/6638355485#step:21:208)
```

I will retry tomorrow; if it doesn't pass need to dig in more seriously.
